spring:
  application:
    name: produtos
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: batatinha
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /bd